### ISSUE TITLE
Update best practices to use markdown instead of/in addition to PDFs

### ISSUE THREAD

**Issue by ebuchman** [cosmos/governance#1]
Current practice is to draft proposals in private, paste them into the forums, and then post them as PDFs to IPFS.

There's many ways we could improve on this. One would be to draft proposals as markdown files on github, for instance in this repo or a fork. Markdown files can still be compiled easily to PDF (eg. with `pandoc`) and posted to IPFS, but we can also just post markdown files directly to IPFS! They can also be viewed easily on IPFS through their markdown viewer, for instance I posted the best_practices.md doc to ipfs, with CID QmbkQNtCAdR1CNbFE8ujub2jcpwUcmSRpSCg8gVWrTHSWD. You can view the rendered markdown at: https://ipfs.io/ipfs/QmTkzDwWqPbnAh5YiV5VwcTLnGdwSNsNTn2aDxdXBFca7D/example#/ipfs/QmbkQNtCAdR1CNbFE8ujub2jcpwUcmSRpSCg8gVWrTHSWD

Ultimately would be great if we could leverage Github as canonical reference, though unfortunately it's not censorship resistant. One issue with current Cosmos Hub governance is there's no way to modify a proposal once it's launched. While in theory this is a good thing, in practice it makes the system cumbersome. This is especially true for text proposals, which are technically non binding as they don't cause direct changes, so it may be valuable in certain cases to evolve them and have governance effectively commit to delegate the final form of a proposal to some small group of reviewers/committers. 

Anyways, such processes are left for future experiments, but for now we should at least promote posting markdown to IPFS over PDF ! Or at least offer both :)

**Comment by glandua** [comment]
I'd like to see improved signalling systems in the co-creative process of proposal generation.  Threaded discussions and markdown instead of PDF is a good start.  Having polls that note both engagement and preference is also useful (testing ideas and components of ideas).  I take some inspiration from the non-blockchain project www.loomio.org (https://github.com/loomio) which is open source and perhaps could plug in to the hub or other blockchains for some sort of on-off chain hybrid for threaded conversations, signally, a final vote about specific software upgrades (or fund dispersal).  Just a vision here.  I really like the simple step of a substantial portion of the process of a governance proposal taking place on github, but I'd also recommend some simple tools like polling and other simple signaling tools.

**Comment by ebuchman** [comment]
Should we try out this github polling extension thing?

/polls "Yes lets do it" "Yes but let me first signal how cool this is, aren't we fortunate that Github is an extensible platform? Shame its still closed source" "No, this is stupid" "I don't care, so long as you all vote in your respective federal elections"

**Comment by ebuchman** [comment]
Seems like some minor improvements on https://github.com/apex/gh-polls could suite our needs? I'm trying it out in #7 - you can already vote there. Not sure how to see who voted what though. Also can't get it working through the bot yet I just generated the poll from https://app.gh-polls.com/ and copied the markdown in

**Comment by dcwalk** [comment]
The current documentation mentions the use of markdown on the IPFS viewer: https://github.com/cosmos/governance/blob/master/submitting.md, however does not promote them or explicitly discourage PDFs, maybe we can consider that meeting the initial issue described here and close, or mark as stale.

Envisioning signalling improvements to the process perhaps can be taken up in a different way? There are definitely gaps and paint points around the creative and collaborative stage of proposal building and it would be great to improve forms of signalling :)

**Comment by dcwalk** [comment]
Going to close out in this repo as part of merge into Gaia. Please re-ticket in https://github.com/cosmos/gaia/
